# Generated by Django 5.1.7 on 2025-05-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
