# Generated by Django 5.1.7 on 2025-05-09 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_book_image_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_alt',
        ),
    ]
